### ISSUE TITLE
GSW0063 and GSW0064

### ISSUE THREAD

**Issue by lb42** [COST-ELTeC/ELTeC-gsw#1]
These appear to be two volumes of the same work, so should not be included as two texts. Our practice is to include the whole of multivolume works as a single text.

Also, the second volume (GSW0064) starts with chapter 26, and the first ends with chapter 24. What happened to chapter 25 ?!

**Comment by giuliagrisot** [comment]
Hi Lou, thanks for this, and sorry I just saw the message! I'll look into it asap. Thanks!

**Comment by lb42** [comment]
Very odd. I don't know why I thought chapter 25 was missing! It's clearly there now.
But the two files really should be combined to form one.
